services:
  bank-go:
    build:
      dockerfile: Dockerfile
      args:
        - VERSION=1.0
    network_mode: host
    ports:
      - "80:8080"
    volumes:
      - .:/app:cached
    depends_on:
      - bank-db
  bank-db:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=postgres
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
